### PR TITLE
Make ProbabilityFn not be an instance of AsymmetricRelation

### PR DESCRIPTION
**Pull request by nordlow**
Make `ProbabilityFn` no longer be an instance of `AsymmetricRelation` since `AsymmetricRelation` is a subclass of `BinaryRelation` which conflicts with `ProbabilityFn` being a unary function.

### CODE REVIEW

**Comment by arademaker** [comment]
Excellent catch! @apease the new interface doesn't catch does valence errors?

**Comment by nordlow** [comment]
> Excellent catch! @apease the new interface doesn't catch does valence errors?

To be honest, I didn't catch these latest PR. My parser did. ;)

**Comment by arademaker** [comment]
Are you writing a parser for KIF files? Can you tell us more? Maybe we can start a wiki adding a page for 'projects using SUMO', what do you think? 

https://github.com/ontologyportal/sumo/wiki

**Comment by nordlow** [comment]
> Are you writing a parser for KIF files? Can you tell us more? Maybe we can start a wiki adding a page for 'projects using SUMO', what do you think?
> 
> https://github.com/ontologyportal/sumo/wiki

I would like to but my project (n:th order knowledge base) is currenly in stealth mode since I have invested years in it full time so far. I might decide to split it out into an open source part and a closed source part but that's not gonna happen soon, unfortunately.

**Pull request merged**
