### PR TITLE
Jenniech

### PR DESCRIPTION
**Pull request by jenniech**
Dear Adam,
Please merge the latest version of Geography.kif and Weather.kif to master if they look alright to you.
I will work on the weather questions as discussed.
Thank you!

### CODE REVIEW

**Comment by apease** [comment]
very minor typographic considerations

- remove space at end (geographicSubregion NortheasternPacificOcean NorthPacificOcean )
- Weather.kif line 713 blank line between rules
- indentation - two arguments to holdDuring at same indent level
(=>
  (and
    (instance ?DUST DustStorm)
    (instance ?PLACE GeographicArea)
    (eventLocated ?DUST ?PLACE))
  (holdsDuring
    (WhenFn ?DUST)
      (modalAttribute
        (attribute ?PLACE BadAirQuality) Likely)))

**Comment by jenniech** [comment]
Dear Adam,
I have revised the files as suggested and added a couple of new terms. Please check and merge if they look alright.
Jennie

**Review by apease — COMMENTED** [review]
(Documentation RedFlagSwimmingCondition EnglishLanguage "A &%RedFlag is &attribute to a &%SurfZone when its

should be

(documentation RedFlagSwimmingCondition EnglishLanguage "A &%RedFlagSwimmingCondition is an &%attribute of a &%SurfZone when its

**Comment by jenniech** [comment]
Dear Adam,
I have just fixed "documentation".
Jennie

**Pull request merged**
