### PR TITLE
Add noun genders

### PR DESCRIPTION
**Pull request by nordlow**
See https://github.com/ontologyportal/sumo/issues/124.

### CODE REVIEW

**Comment by apease** [comment]
Hi Per,
  Many thanks for this new content.  Each new terms should also have a documentation statement.  To avoid being language-centric, it appears that it would be good to have animate-inanimate as genders too.  In addition, there should be some rules to define the terms.  Maybe you could broaden the argument from Noun to Word, since adjectives and articles also have gender.  Then you could state for example that if there's a sentence with a noun that has a certain gender, that in a romance language the determiner or adjective that refers to the noun must have the same gender.  Since this content is about the syntax of languages, which seems quite specific to me, I'd also suggest placing it in Languages.kif

**Comment by nordlow** [comment]
Ok, great. I believe the rule of definition article also holds form German.

**Comment by nordlow** [comment]
Add some docs.

**Comment by arademaker** [comment]
Do we have any issue open related to this PR? It would be interesting to have a place with the goals that @nordlow are trying to achieve.

**Comment by nordlow** [comment]
Shall I change 

```
(instance nounGender TernaryPredicate)
(domain nounGender 1 Noun)
(domain nounGender 2 NaturalLanguage)
(domain nounGender 3 GrammaticalGender)
```

to

```
(instance wordGender TernaryPredicate)
(domain wordGender 1 Word)
(domain wordGender 2 NaturalLanguage)
(domain wordGender 3 GrammaticalGender)
```

?

**Pull request merged**
