### PR TITLE
Changed the currencyType to EuroDollar for the 19 Eurozone members.

### PR DESCRIPTION
**Pull request by jefft0**
The 19 Eurozone countries are listed here: http://ec.europa.eu/economy_finance/euro/adoption/euro_area/index_en.htm

### CODE REVIEW

**Comment by jefft0** [comment]
Should currencyType be a SingleValuedRelation? I ask because EuropeanMonetaryUnion already has the rule below for the currencyType of a EuropeanMonetaryUnion member, and `(member Spain EuropeanMonetaryUnion)`. So, a consistency checker would flag the contradiction with `(currencyType Spain SpanishPeseta)`.

    (=>
      (and
        (instance ?AREA Nation)
        (member ?AREA EuropeanMonetaryUnion))
      (currencyType ?AREA EuroDollar))

**Comment by apease** [comment]
yes I agree

**Comment by jefft0** [comment]
I want to follow your preferred workflow. Would I open a pull request to make currencyType a SingleValuedRelation?

**Comment by apease** [comment]
Hi Jeff,
   I'm not sure I have a preferred Git workflow, since I'm an old CVS 
guy and new to Git :-). Maybe you could advise me on what is typical.

Adam

On 05/16/2016 02:05 AM, Jeff Thompson wrote:
> I want to follow your preferred workflow. Would I open a pull request to
> make currencyType a SingleValuedRelation?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/ontologyportal/sumo/pull/6#issuecomment-219381261>
>

-- 
-------------------
Adam Pease
http://www.ontologyportal.org
http://www.articulatesoftware.com
http://www.adampease.org

**Comment by jefft0** [comment]
Typically, the merits of a proposed change are discussed in a pull request like we're doing here. For more general changes and new feature requests, one opens an issue, like someone did for issue #4. When a pull request comment mentions an issue, it is automatically linked (as just happened for issue number 4). Technically, this is all "GitHub workflow". The question is whether the people who are used to working on SUMO are okay with discussion on a GitHub pull request or issue, or whether you have a preferred established system (like an email list somewhere).

**Comment by apease** [comment]
Hi Jeff,
   The email list I used when SUMO was on SourceForge got very little 
traffic. So I think you could use GitHub pull request comments, at least 
for now.

all the best,
Adam

On 05/16/2016 06:13 AM, Jeff Thompson wrote:
> Typically, the merits of a proposed change are discussed in a pull
> request like we're doing here. For more general changes and new feature
> requests, one opens an issue, like someone did for issue #4
> <https://github.com/ontologyportal/sumo/issues/4>. When a pull request
> comment mentions an issue, it is automatically linked (as just happened
> for issue number 4). Technically, this is all "GitHub workflow". The
> question is whether the people who are used to working on SUMO are okay
> with discussion on a GitHub pull request or issue, or whether you have a
> preferred established system (like an email list somewhere).
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/ontologyportal/sumo/pull/6#issuecomment-219421438>
>

-- 
-------------------
Adam Pease
http://www.ontologyportal.org
http://www.articulatesoftware.com
http://www.adampease.org

**Comment by jefft0** [comment]
I updated the file to add (instance currencyType SingleValuedRelation).

**Comment by jefft0** [comment]
Thanks for merging. When do the changes show up in the online SUMO browser? http://54.183.42.206:8080/sigma/Browse.jsp?kb=SUMO&lang=EnglishLanguage&flang=SUO-KIF&term=Spain

**Comment by apease** [comment]
Hi Jeff,
   It's rather random, either by request (feel free to request:-) or 
when I feel like I've stacked up enough additions or changes to make a 
different (subjective of course), or if some bug has been fixed.
   A nice project might be to do a cron script that would pull all the 
changes from Git and restart Sigma. hint, hint :-)

Adam

On 05/28/2016 11:41 AM, Jeff Thompson wrote:
> Thanks for merging. When do the changes show up in the online SUMO
> browser?
> http://54.183.42.206:8080/sigma/Browse.jsp?kb=SUMO&lang=EnglishLanguage&flang=SUO-KIF&term=Spain
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/ontologyportal/sumo/pull/6#issuecomment-222323408>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACBvHfwZFEMSiy7SfKaog5enXUcqR1RTks5qGIxrgaJpZM4IZwTz>.
>

-- 
-------------------
Adam Pease
http://www.ontologyportal.org
http://www.articulatesoftware.com
http://www.adampease.org

**Comment by jefft0** [comment]
Hint taken. I'll take a look at the cron script when I get back from travels in about a week. What platform (Linux, Mac) is the public browser running on now?

**Comment by apease** [comment]
Hi Jeff,
   Once I started thinking about how to do this I couldn't stop.  Sorry. 
  Here's what I came up with

cd /home/apease/workspace/sumo
git pull
cp *.kif /home/apease/Sigma/KBs
cp -R Translations /home/apease/Sigma/KBs
cp -R WordNetMappings /home/apease/Sigma/KBs
/var/tomcat/apache-tomcat-8.0.26/bin/shutdown.sh
echo "waiting 10 seconds"
sleep 10
/var/tomcat/apache-tomcat-8.0.26/bin/startup.sh
echo "waiting 30 seconds"
sleep 30
curl -d userName="user" -d password="user" 
"http://localhost:8080/sigma/KBs.jsp?kb=SUMO&lang=EnglishLanguage&flang=SUO-KIF&term=Object" 
 > result.html


I'll try fussing with cron now.

One wrinkle I don't think I have time to figure out would be how to send 
myself a "Sigma rebooted" email, since that would require installing a 
mail server, which I don't have experience in configuring safely.  If 
you do, that might be something to try.  I'd also be interested in 
hearing about the sorts of things you might be interested in doing.  I 
really appreciate your help fixing the currency facts.

all the best,
Adam


On 05/29/2016 03:03 AM, Jeff Thompson wrote:
> Hint taken. I'll take a look at the cron script when I get back from
> travels in about a week. What platform (Linux, Mac) is the public
> browser running on now?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/ontologyportal/sumo/pull/6#issuecomment-222352642>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACBvHXItWBWll1xktlMgrJIoNrz1ZjWSks5qGWRhgaJpZM4IZwTz>.
>

-- 
-------------------
Adam Pease
http://www.ontologyportal.org
http://www.articulatesoftware.com
http://www.adampease.org

**Comment by apease** [comment]
Hi Jeff,
   I've added my script to /etc/cron.weekly so if I've done it right, 
from now on the public Sigma installation will fetch all the latest 
knowledge base files and WordNet mappings from Git and update automatically.

all the best,
Adam

On 05/29/2016 03:03 AM, Jeff Thompson wrote:
> Hint taken. I'll take a look at the cron script when I get back from
> travels in about a week. What platform (Linux, Mac) is the public
> browser running on now?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/ontologyportal/sumo/pull/6#issuecomment-222352642>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACBvHXItWBWll1xktlMgrJIoNrz1ZjWSks5qGWRhgaJpZM4IZwTz>.
>

-- 
-------------------
Adam Pease
http://www.ontologyportal.org
http://www.articulatesoftware.com
http://www.adampease.org

**Comment by arademaker** [comment]
This issue is still open?! What have to be done here?

**Comment by jefft0** [comment]
I don't have any more questions. You can close it.

**Pull request merged**
