### PR TITLE
Add missing brace

### PR DESCRIPTION
**Pull request by nordlow**

### CODE REVIEW

**Comment by apease** [comment]
thanks for catching this but the paren actually goes at the end of the antecedent, will push a fix shortly

**Comment by nordlow** [comment]
BTW, why is there now syntax checking in the CI?

**Comment by apease** [comment]
sorry, what is CI?

**Comment by nordlow** [comment]
Continuous integration. 😊

**Comment by apease** [comment]
I haven't set up any syntax checking, although now that I have the SUMOjEdit system, it could become part of the standard process for SUMO development

**Pull request closed without merging**
