### PR TITLE
Add axiom: possession transfers through its parts

### PR DESCRIPTION
**Pull request by nordlow**
Inspired by Douglas Lenats latest talk at time [2:39](https://youtu.be/v2rK40bNrrY?t=159).

Maybe this could be generalized somehow?

### CODE REVIEW

**Comment by nordlow** [comment]
Ping, @apease

**Comment by apease** [comment]
reformulated proposed axiom to 

(=>
  (and
    (holdsDuring ?T
      (possesses ?PERSON ?OBJ))
    (part ?P ?OBJ))
  (holdsDuring ?T
    (possesses ?PERSON ?P)))

added to Merge.kif

**Comment by nordlow** [comment]
Thanks!

**Comment by arademaker** [comment]
Just to better document the changes. The commit that justify closing this PR IS bde57d9ecba47c564a85b63fc07e4422db0bd6b4

**Pull request closed without merging**
